/** ISO2 → Türkçe ülke adı (harita ve listelerde gösterim) */
export const COUNTRY_NAMES_TR: Record<string, string> = {
  MA: "Fas",
  TN: "Tunus",
  DZ: "Cezayir",
  LY: "Libya",
  EG: "Mısır",
  SD: "Sudan",
  ET: "Etiyopya",
  KE: "Kenya",
  TZ: "Tanzanya",
  UG: "Uganda",
  RW: "Ruanda",
  NG: "Nijerya",
  GH: "Gana",
  SN: "Senegal",
  ZA: "Güney Afrika",
  NA: "Namibya",
  TR: "Türkiye",
  CY: "Kıbrıs",
  GR: "Yunanistan",
  BG: "Bulgaristan",
  RO: "Romanya",
  MD: "Moldova",
  UA: "Ukrayna",
  BY: "Belarus",
  RU: "Rusya",
  ES: "İspanya",
  PT: "Portekiz",
  IT: "İtalya",
  FR: "Fransa",
  DE: "Almanya",
  NL: "Hollanda",
  BE: "Belçika",
  GB: "Birleşik Krallık",
  IE: "İrlanda",
  CH: "İsviçre",
  AT: "Avusturya",
  CZ: "Çekya",
  SK: "Slovakya",
  PL: "Polonya",
  HU: "Macaristan",
  SI: "Slovenya",
  HR: "Hırvatistan",
  BA: "Bosna Hersek",
  ME: "Karadağ",
  RS: "Sırpistan",
  XK: "Kosova",
  MK: "Kuzey Makedonya",
  AL: "Arnavutluk",
  NO: "Norveç",
  SE: "İsveç",
  FI: "Finlandiya",
  DK: "Danimarka",
  IS: "İzlanda",
  GE: "Gürcistan",
  AZ: "Azerbaycan",
  AM: "Ermenistan",
  IR: "İran",
  IQ: "Irak",
  SY: "Suriye",
  JO: "Ürdün",
  IL: "İsrail",
  PS: "Filistin",
  LB: "Lübnan",
  SA: "Suudi Arabistan",
  QA: "Katar",
  BH: "Bahreyn",
  KW: "Kuveyt",
  OM: "Umman",
  AE: "Birleşik Arap Emirlikleri",
  UZ: "Özbekistan",
  KZ: "Kazakistan",
  KG: "Kırgızistan",
  TM: "Türkmenistan",
  TJ: "Tacikistan",
  AF: "Afganistan",
  JP: "Japonya",
  KR: "Güney Kore",
  CN: "Çin",
  TW: "Tayvan",
  HK: "Hong Kong",
  TH: "Tayland",
  VN: "Vietnam",
  KH: "Kamboçya",
  LA: "Laos",
  MM: "Myanmar",
  ID: "Endonezya",
  MY: "Malezya",
  SG: "Singapur",
  PH: "Filipinler",
  IN: "Hindistan",
  PK: "Pakistan",
  BD: "Bangladeş",
  LK: "Sri Lanka",
  NP: "Nepal",
  MV: "Maldivler",
  MN: "Moğolistan",
  US: "ABD",
  CA: "Kanada",
  MX: "Meksika",
  CU: "Küba",
  BR: "Brezilya",
  AR: "Arjantin",
  CL: "Şili",
  PE: "Peru",
  CO: "Kolombiya",
  EC: "Ekvador",
  VE: "Venezuela",
  BO: "Bolivya",
  PY: "Paraguay",
  UY: "Uruguay",
  PA: "Panama",
  CR: "Kosta Rika",
  GT: "Guatemala",
  JM: "Jamaika",
  NI: "Nikaragua",
  HN: "Honduras",
  SV: "El Salvador",
  BZ: "Belize",
  DO: "Dominik Cumhuriyeti",
  AU: "Avustralya",
  NZ: "Yeni Zelanda",
  FJ: "Fiji",
  LU: "Lüksemburg",
  MT: "Malta",
  EE: "Estonya",
  LV: "Letonya",
  LT: "Litvanya",
};

export function getCountryDisplayName(code: string, fallback?: string): string {
  return COUNTRY_NAMES_TR[code] ?? fallback ?? code;
}
