export type CountryDef = { code: string; name: string };

export const COUNTRY_ALIASES_DATA: Record<string, CountryDef> = {
  fas: { code: "MA", name: "Morocco" },
  morocco: { code: "MA", name: "Morocco" },
  tunus: { code: "TN", name: "Tunisia" },
  tunisia: { code: "TN", name: "Tunisia" },
  cezayir: { code: "DZ", name: "Algeria" },
  algeria: { code: "DZ", name: "Algeria" },
  libya: { code: "LY", name: "Libya" },
  misir: { code: "EG", name: "Egypt" },
  egypt: { code: "EG", name: "Egypt" },
  sudan: { code: "SD", name: "Sudan" },
  etiyopya: { code: "ET", name: "Ethiopia" },
  ethiopia: { code: "ET", name: "Ethiopia" },
  kenya: { code: "KE", name: "Kenya" },
  tanzanya: { code: "TZ", name: "Tanzania" },
  tanzania: { code: "TZ", name: "Tanzania" },
  uganda: { code: "UG", name: "Uganda" },
  ruanda: { code: "RW", name: "Rwanda" },
  rwanda: { code: "RW", name: "Rwanda" },
  nijerya: { code: "NG", name: "Nigeria" },
  nigeria: { code: "NG", name: "Nigeria" },
  gana: { code: "GH", name: "Ghana" },
  ghana: { code: "GH", name: "Ghana" },
  senegal: { code: "SN", name: "Senegal" },
  guneyafrika: { code: "ZA", name: "South Africa" },
  southafrica: { code: "ZA", name: "South Africa" },
  namibya: { code: "NA", name: "Namibia" },
  namibia: { code: "NA", name: "Namibia" },
  turkiye: { code: "TR", name: "Turkey" },
  turkey: { code: "TR", name: "Turkey" },
  kibris: { code: "CY", name: "Cyprus" },
  cyprus: { code: "CY", name: "Cyprus" },
  yunanistan: { code: "GR", name: "Greece" },
  greece: { code: "GR", name: "Greece" },
  bulgaristan: { code: "BG", name: "Bulgaria" },
  bulgaria: { code: "BG", name: "Bulgaria" },
  romanya: { code: "RO", name: "Romania" },
  romania: { code: "RO", name: "Romania" },
  moldova: { code: "MD", name: "Moldova" },
  ukrayna: { code: "UA", name: "Ukraine" },
  ukraine: { code: "UA", name: "Ukraine" },
  belarus: { code: "BY", name: "Belarus" },
  rusya: { code: "RU", name: "Russia" },
  russia: { code: "RU", name: "Russia" },
  ispanya: { code: "ES", name: "Spain" },
  spain: { code: "ES", name: "Spain" },
  portekiz: { code: "PT", name: "Portugal" },
  portugal: { code: "PT", name: "Portugal" },
  italya: { code: "IT", name: "Italy" },
  italy: { code: "IT", name: "Italy" },
  fransa: { code: "FR", name: "France" },
  france: { code: "FR", name: "France" },
  almanya: { code: "DE", name: "Germany" },
  germany: { code: "DE", name: "Germany" },
  hollanda: { code: "NL", name: "Netherlands" },
  netherlands: { code: "NL", name: "Netherlands" },
  belcika: { code: "BE", name: "Belgium" },
  belgium: { code: "BE", name: "Belgium" },
  ingiltere: { code: "GB", name: "United Kingdom" },
  uk: { code: "GB", name: "United Kingdom" },
  irlanda: { code: "IE", name: "Ireland" },
  ireland: { code: "IE", name: "Ireland" },
  isvicre: { code: "CH", name: "Switzerland" },
  switzerland: { code: "CH", name: "Switzerland" },
  avusturya: { code: "AT", name: "Austria" },
  austria: { code: "AT", name: "Austria" },
  cekya: { code: "CZ", name: "Czechia" },
  czechia: { code: "CZ", name: "Czechia" },
  slovakya: { code: "SK", name: "Slovakia" },
  slovakia: { code: "SK", name: "Slovakia" },
  polonya: { code: "PL", name: "Poland" },
  poland: { code: "PL", name: "Poland" },
  macaristan: { code: "HU", name: "Hungary" },
  hungary: { code: "HU", name: "Hungary" },
  slovenya: { code: "SI", name: "Slovenia" },
  slovenia: { code: "SI", name: "Slovenia" },
  hirvatistan: { code: "HR", name: "Croatia" },
  croatia: { code: "HR", name: "Croatia" },
  bosna: { code: "BA", name: "Bosnia and Herzegovina" },
  bosnia: { code: "BA", name: "Bosnia and Herzegovina" },
  karadag: { code: "ME", name: "Montenegro" },
  montenegro: { code: "ME", name: "Montenegro" },
  sirbistan: { code: "RS", name: "Serbia" },
  serbia: { code: "RS", name: "Serbia" },
  kosova: { code: "XK", name: "Kosovo" },
  kosovo: { code: "XK", name: "Kosovo" },
  makedonya: { code: "MK", name: "North Macedonia" },
  macedonia: { code: "MK", name: "North Macedonia" },
  arnavutluk: { code: "AL", name: "Albania" },
  albania: { code: "AL", name: "Albania" },
  norvec: { code: "NO", name: "Norway" },
  norway: { code: "NO", name: "Norway" },
  isvec: { code: "SE", name: "Sweden" },
  sweden: { code: "SE", name: "Sweden" },
  finlandiya: { code: "FI", name: "Finland" },
  finland: { code: "FI", name: "Finland" },
  danimarka: { code: "DK", name: "Denmark" },
  denmark: { code: "DK", name: "Denmark" },
  izlanda: { code: "IS", name: "Iceland" },
  iceland: { code: "IS", name: "Iceland" },
  gurcistan: { code: "GE", name: "Georgia" },
  georgia: { code: "GE", name: "Georgia" },
  azerbaycan: { code: "AZ", name: "Azerbaijan" },
  azerbaijan: { code: "AZ", name: "Azerbaijan" },
  ermenistan: { code: "AM", name: "Armenia" },
  armenia: { code: "AM", name: "Armenia" },
  iran: { code: "IR", name: "Iran" },
  irak: { code: "IQ", name: "Iraq" },
  iraq: { code: "IQ", name: "Iraq" },
  suriye: { code: "SY", name: "Syria" },
  syria: { code: "SY", name: "Syria" },
  urdun: { code: "JO", name: "Jordan" },
  jordan: { code: "JO", name: "Jordan" },
  israil: { code: "IL", name: "Israel" },
  israel: { code: "IL", name: "Israel" },
  filistin: { code: "PS", name: "Palestine" },
  palestine: { code: "PS", name: "Palestine" },
  lubnan: { code: "LB", name: "Lebanon" },
  lebanon: { code: "LB", name: "Lebanon" },
  suudiarabistan: { code: "SA", name: "Saudi Arabia" },
  saudiarabia: { code: "SA", name: "Saudi Arabia" },
  katar: { code: "QA", name: "Qatar" },
  qatar: { code: "QA", name: "Qatar" },
  bahreyn: { code: "BH", name: "Bahrain" },
  bahrain: { code: "BH", name: "Bahrain" },
  kuveyt: { code: "KW", name: "Kuwait" },
  kuwait: { code: "KW", name: "Kuwait" },
  oman: { code: "OM", name: "Oman" },
  dubai: { code: "AE", name: "United Arab Emirates" },
  uae: { code: "AE", name: "United Arab Emirates" },
  ozbekistan: { code: "UZ", name: "Uzbekistan" },
  uzbekistan: { code: "UZ", name: "Uzbekistan" },
  kazakistan: { code: "KZ", name: "Kazakhstan" },
  kazakhstan: { code: "KZ", name: "Kazakhstan" },
  kirgizistan: { code: "KG", name: "Kyrgyzstan" },
  kyrgyzstan: { code: "KG", name: "Kyrgyzstan" },
  turkmenistan: { code: "TM", name: "Turkmenistan" },
  tacikistan: { code: "TJ", name: "Tajikistan" },
  tajikistan: { code: "TJ", name: "Tajikistan" },
  afganistan: { code: "AF", name: "Afghanistan" },
  afghanistan: { code: "AF", name: "Afghanistan" },
  japonya: { code: "JP", name: "Japan" },
  japan: { code: "JP", name: "Japan" },
  kore: { code: "KR", name: "South Korea" },
  korea: { code: "KR", name: "South Korea" },
  guneykore: { code: "KR", name: "South Korea" },
  cin: { code: "CN", name: "China" },
  china: { code: "CN", name: "China" },
  tayvan: { code: "TW", name: "Taiwan" },
  taiwan: { code: "TW", name: "Taiwan" },
  hongkong: { code: "HK", name: "Hong Kong" },
  tayland: { code: "TH", name: "Thailand" },
  thailand: { code: "TH", name: "Thailand" },
  vietnam: { code: "VN", name: "Vietnam" },
  kambocya: { code: "KH", name: "Cambodia" },
  cambodia: { code: "KH", name: "Cambodia" },
  laos: { code: "LA", name: "Laos" },
  myanmar: { code: "MM", name: "Myanmar" },
  endonezya: { code: "ID", name: "Indonesia" },
  indonesia: { code: "ID", name: "Indonesia" },
  malezya: { code: "MY", name: "Malaysia" },
  malaysia: { code: "MY", name: "Malaysia" },
  singapur: { code: "SG", name: "Singapore" },
  singapore: { code: "SG", name: "Singapore" },
  filipinler: { code: "PH", name: "Philippines" },
  philippines: { code: "PH", name: "Philippines" },
  hindistan: { code: "IN", name: "India" },
  india: { code: "IN", name: "India" },
  pakistan: { code: "PK", name: "Pakistan" },
  banglades: { code: "BD", name: "Bangladesh" },
  bangladesh: { code: "BD", name: "Bangladesh" },
  srilanka: { code: "LK", name: "Sri Lanka" },
  nepal: { code: "NP", name: "Nepal" },
  maldivler: { code: "MV", name: "Maldives" },
  maldives: { code: "MV", name: "Maldives" },
  mongolya: { code: "MN", name: "Mongolia" },
  mongolia: { code: "MN", name: "Mongolia" },
  abd: { code: "US", name: "United States" },
  usa: { code: "US", name: "United States" },
  amerika: { code: "US", name: "United States" },
  unitedstates: { code: "US", name: "United States" },
  kanada: { code: "CA", name: "Canada" },
  canada: { code: "CA", name: "Canada" },
  meksika: { code: "MX", name: "Mexico" },
  mexico: { code: "MX", name: "Mexico" },
  kuba: { code: "CU", name: "Cuba" },
  cuba: { code: "CU", name: "Cuba" },
  brezilya: { code: "BR", name: "Brazil" },
  brazil: { code: "BR", name: "Brazil" },
  arjantin: { code: "AR", name: "Argentina" },
  argentina: { code: "AR", name: "Argentina" },
  sili: { code: "CL", name: "Chile" },
  chile: { code: "CL", name: "Chile" },
  peru: { code: "PE", name: "Peru" },
  kolombiya: { code: "CO", name: "Colombia" },
  colombia: { code: "CO", name: "Colombia" },
  ekvador: { code: "EC", name: "Ecuador" },
  ecuador: { code: "EC", name: "Ecuador" },
  venezuela: { code: "VE", name: "Venezuela" },
  bolivya: { code: "BO", name: "Bolivia" },
  bolivia: { code: "BO", name: "Bolivia" },
  paraguay: { code: "PY", name: "Paraguay" },
  uruguay: { code: "UY", name: "Uruguay" },
  panama: { code: "PA", name: "Panama" },
  kostarika: { code: "CR", name: "Costa Rica" },
  costarica: { code: "CR", name: "Costa Rica" },
  guatemala: { code: "GT", name: "Guatemala" },
  jamaika: { code: "JM", name: "Jamaica" },
  jamaica: { code: "JM", name: "Jamaica" },
  avustralya: { code: "AU", name: "Australia" },
  australia: { code: "AU", name: "Australia" },
  yenizelanda: { code: "NZ", name: "New Zealand" },
  newzealand: { code: "NZ", name: "New Zealand" },
  fiji: { code: "FJ", name: "Fiji" },
};

export const ISO2_COUNTRY: Record<string, CountryDef> = {
  MA: { code: "MA", name: "Morocco" },
  TN: { code: "TN", name: "Tunisia" },
  DZ: { code: "DZ", name: "Algeria" },
  LY: { code: "LY", name: "Libya" },
  EG: { code: "EG", name: "Egypt" },
  TR: { code: "TR", name: "Turkey" },
  GR: { code: "GR", name: "Greece" },
  ES: { code: "ES", name: "Spain" },
  PT: { code: "PT", name: "Portugal" },
  IT: { code: "IT", name: "Italy" },
  FR: { code: "FR", name: "France" },
  DE: { code: "DE", name: "Germany" },
  NL: { code: "NL", name: "Netherlands" },
  BE: { code: "BE", name: "Belgium" },
  GB: { code: "GB", name: "United Kingdom" },
  CH: { code: "CH", name: "Switzerland" },
  AT: { code: "AT", name: "Austria" },
  CZ: { code: "CZ", name: "Czechia" },
  PL: { code: "PL", name: "Poland" },
  HU: { code: "HU", name: "Hungary" },
  RS: { code: "RS", name: "Serbia" },
  GE: { code: "GE", name: "Georgia" },
  AZ: { code: "AZ", name: "Azerbaijan" },
  UZ: { code: "UZ", name: "Uzbekistan" },
  AE: { code: "AE", name: "United Arab Emirates" },
  SA: { code: "SA", name: "Saudi Arabia" },
  QA: { code: "QA", name: "Qatar" },
  JP: { code: "JP", name: "Japan" },
  KR: { code: "KR", name: "South Korea" },
  CN: { code: "CN", name: "China" },
  TH: { code: "TH", name: "Thailand" },
  VN: { code: "VN", name: "Vietnam" },
  ID: { code: "ID", name: "Indonesia" },
  MY: { code: "MY", name: "Malaysia" },
  SG: { code: "SG", name: "Singapore" },
  PH: { code: "PH", name: "Philippines" },
  IN: { code: "IN", name: "India" },
  US: { code: "US", name: "United States" },
  CA: { code: "CA", name: "Canada" },
  MX: { code: "MX", name: "Mexico" },
  BR: { code: "BR", name: "Brazil" },
  AR: { code: "AR", name: "Argentina" },
  CL: { code: "CL", name: "Chile" },
  PE: { code: "PE", name: "Peru" },
  CO: { code: "CO", name: "Colombia" },
  AU: { code: "AU", name: "Australia" },
  NZ: { code: "NZ", name: "New Zealand" },
  ZA: { code: "ZA", name: "South Africa" },
  KE: { code: "KE", name: "Kenya" },
  NG: { code: "NG", name: "Nigeria" },
  RU: { code: "RU", name: "Russia" },
  UA: { code: "UA", name: "Ukraine" },
  RO: { code: "RO", name: "Romania" },
  BG: { code: "BG", name: "Bulgaria" },
  NO: { code: "NO", name: "Norway" },
  SE: { code: "SE", name: "Sweden" },
  FI: { code: "FI", name: "Finland" },
  DK: { code: "DK", name: "Denmark" },
  HR: { code: "HR", name: "Croatia" },
  BA: { code: "BA", name: "Bosnia and Herzegovina" },
  AL: { code: "AL", name: "Albania" },
  MK: { code: "MK", name: "North Macedonia" },
  XK: { code: "XK", name: "Kosovo" },
  ME: { code: "ME", name: "Montenegro" },
  IQ: { code: "IQ", name: "Iraq" },
  IR: { code: "IR", name: "Iran" },
  JO: { code: "JO", name: "Jordan" },
  LB: { code: "LB", name: "Lebanon" },
  IL: { code: "IL", name: "Israel" },
  KZ: { code: "KZ", name: "Kazakhstan" },
  PK: { code: "PK", name: "Pakistan" },
  LK: { code: "LK", name: "Sri Lanka" },
  NP: { code: "NP", name: "Nepal" },
  MV: { code: "MV", name: "Maldives" },
  CU: { code: "CU", name: "Cuba" },
  EC: { code: "EC", name: "Ecuador" },
};

export const COUNTRY_KEYS_SORTED = Object.keys(COUNTRY_ALIASES_DATA).sort(
  (a, b) => b.length - a.length,
);
